# -*- coding: utf-8 -*-
"""Fruit Classification Model By Using Advanced AI Technique.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyTbbpdHzpHXjpWMyjr8mbknt3SNnO5_
"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import numpy as np
from PIL import Image

input_shape =(224,224,3)
epochs = 5
batch_size = 32
num_classes =5

train_path ='/content/drive/MyDrive/fruits/fruits/Fruits Classification/train'
test_path ='/content/drive/MyDrive/fruits/fruits/Fruits Classification/test'

train_gen = ImageDataGenerator(
    rescale = 1./255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)
train_data = train_gen.flow_from_directory(
    train_path,
    target_size = (224,224),
    batch_size = 32,
    class_mode = 'categorical',
    subset = 'training'
)

test_gen =ImageDataGenerator(
    rescale = 1./255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_data = test_gen.flow_from_directory(
    test_path,
    target_size = (224,224),
    batch_size = 32,
    class_mode = 'categorical'
)

import matplotlib.pyplot as plt
images, labels = next(train_data)
plt.figure(figsize=(8,8))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(images[i])
    plt.title(list(train_data.class_indices.keys())[np.argmax(labels[i])])
    plt.axis('off')
plt.tight_layout()
plt.show()

NUTRITION = {
    'apple': {'calories': 52, 'protein': 0.3, 'carbs': 14, 'fiber': 2.4, 'vitamin_c': 4.6},
    'banana': {'calories': 89, 'protein': 1.1, 'carbs': 23, 'fiber': 2.6, 'vitamin_c': 8.7},
    'orange': {'calories': 47, 'protein': 0.9, 'carbs': 12, 'fiber': 2.4, 'vitamin_c': 53.2},
    'strawberry': {'calories': 32, 'protein': 0.7, 'carbs': 8, 'fiber': 2.0, 'vitamin_c': 58.8},
    'grape': {'calories': 69, 'protein': 0.7, 'carbs': 18, 'fiber': 0.9, 'vitamin_c': 3.2},
}

def build_model(num_classes=5):
    base = MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
    base.trainable = False

    x = layers.GlobalAveragePooling2D()(base.output)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.3)(x)
    output = layers.Dense(num_classes, activation='softmax')(x)

    model = Model(base.input, output)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

model = build_model(num_classes=num_classes)
model.fit(train_data, validation_data=test_data, epochs=epochs)
model.save('fruit_model.h5')

def predict_fruit(image_path, model, classes):
    img = Image.open(image_path).convert('RGB').resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    pred = model.predict(img_array, verbose=0)
    class_idx = np.argmax(pred[0])
    confidence = pred[0][class_idx]
    fruit_name = classes[class_idx]

    print(f"\n🍎 Predicted: {fruit_name.upper()}")
    print(f"📊 Confidence: {confidence*100:.2f}%")
    print(f"\n💚 Nutrition (per 100g):")

    nutrition = NUTRITION[fruit_name.lower()]
    print(f"  Calories: {nutrition['calories']} kcal")
    print(f"  Protein: {nutrition['protein']}g")
    print(f"  Carbs: {nutrition['carbs']}g")
    print(f"  Fiber: {nutrition['fiber']}g")
    print(f"  Vitamin C: {nutrition['vitamin_c']}mg")

    return fruit_name, nutrition

if __name__ == "__main__":
    print("Loading model...")
    model = tf.keras.models.load_model('fruit_model.h5')
    classes = list(train_data.class_indices.keys())

    print("\nTesting prediction...")
    test_img = '/content/drive/MyDrive/fruits/fruits/Fruits Classification/test/Apple/Apple (12).png'
    predict_fruit(test_img, model, classes)

